Map<String, List<String>?> nullableMap = {
  "InitConfig": ["databasePath", "customDb"],
  "RecognizeConfig": [
    "onlineProcessingConfig",
    "livePortrait",
    "extPortrait",
    "data",
    "images",
    "imageInputData"
  ],
  "RecognizeConfig2": ["scenario", "image"],
  "ScannerConfig": ["scenario", "livePortrait", "extPortrait", "cameraId"],
  "ScannerConfig2": ["onlineProcessingConfig"],
  "FaceApiSearchParams": ["groupIds"],
  "FaceApiParams": ["searchParams", "proxy", "proxyPassword", "proxyType"],
  "LivenessParams!": [],
  "AuthenticityParams!": ["livenessParams"],
  "GlaresCheckParams!": [],
  "RFIDParams!": [],
  "ImageQA!": [],
  "BackendProcessingConfig": ["rfidServerSideChipVerification", "httpHeaders"],
  "ProcessParams!": ["imageQA", "authenticityParams"],
  "RFIDScenario!": [
    "defaultReadingBufferSize",
    "eDLDataGroups",
    "ePassportDataGroups",
    "eIDDataGroups"
  ],
  "CustomizationColors": [],
  "CustomizationFonts": [],
  "CustomizationImages": [],
  "Customization!": ["colors", "fonts", "images"],
  "Functionality!": [],
  "DocumentsDatabase!": ["countriesNumber", "documentsNumber"],
  "DocReaderVersion!": [],
  "License": ["expiryDate", "countryFilter"],
  "VDSNCData": ["type", "issuingCountry", "signatureAlgorithm"],
  "GraphicField": ["fieldRect"],
  "Symbol": ["rect"],
  "Value": ["boundRect", "rfidOrigin"],
  "TextSource": ["source"],
  "DocumentType": [
    "name",
    "iCAOCode",
    "fDSID",
    "dDescription",
    "dYear",
    "dCountryName"
  ],
  "TransactionInfo!": [],
  "Results": ["authenticityResult"],
  "PAResourcesIssuer": ["friendlyName"],
  "PKDCertificate": ["privateKey"],
  "TccParams!": [],
};
