Map<String, List<String>?> nullableMap = {
  "initConfig": ["databasePath", "customDb"],
  "recognizeConfig": [
    "onlineProcessingConfig",
    "livePortrait",
    "extPortrait",
    "data",
    "images",
    "imageInputData",
  ],
  "recognizeConfig2": ["scenario", "image"],
  "scannerConfig": ["scenario", "livePortrait", "extPortrait", "cameraId"],
  "scannerConfig2": ["onlineProcessingConfig"],
  "onlineProcessingConfig": ["requestHeaders"],
  "faceApiSearchParams": ["groupIds"],
  "faceApiParams": ["searchParams", "proxy", "proxyPassword", "proxyType"],
  "livenessParams!": [],
  "authenticityParams!": ["livenessParams"],
  "glaresCheckParams!": [],
  "rfidParams!": [],
  "imageQA!": [],
  "backendProcessingConfig": ["rfidServerSideChipVerification", "httpHeaders"],
  "processParams!": ["imageQA", "authenticityParams"],
  "rfidScenario!": [
    "defaultReadingBufferSize",
    "eDLDataGroups",
    "ePassportDataGroups",
    "eIDDataGroups",
    "dtcDataGroups",
  ],
  "customization!": ["colors", "fonts", "images"],
  "functionality!": [],
  "documentsDatabase!": ["countriesNumber", "documentsNumber"],
  "docReaderVersion!": [],
  "license": ["expiryDate", "countryFilter"],
  "vdsncData": ["type", "issuingCountry", "signatureAlgorithm"],
  "graphicField": ["fieldRect"],
  "symbol": ["rect"],
  "value": ["boundRect", "rfidOrigin"],
  "textSource": ["source"],
  "documentType": [
    "name",
    "iCAOCode",
    "fDSID",
    "dDescription",
    "dYear",
    "dCountryName",
  ],
  "transactionInfo": ["transactionId", "tag"],
  "results": ["authenticityResult"],
  "paResourcesIssuer": ["friendlyName"],
  "pkdCertificate": ["privateKey"],
  "tccParams!": [],
};
